### ISSUE TITLE
Oni segfaults on startup after upgrading to glibc 2.28

### ISSUE THREAD

**Issue by nesmyslny** [onivim/oni#2497]
Hi!

Thanks for this amazing project :) 
If I can help by providing more information or anything, just let me know.

**Oni Version:** 0.3.6
**Neovim Version (Linux only):** 0.3.1
**Operating System:** Linux (Arch)

**Issue:**
After upgrading glibc to version 2.28, Oni segfaults on startup. Downgrading to glibc 2.27 works around this issue.

**Expected behavior:** Oni starts up.

**Actual behavior:** Segfault on startup

**Steps to reproduce:**
1. Upgrade to glibc 2.28
2. Try to start Oni

**Edit:**
Seems like other projects face the same issue:
* Signal: https://github.com/signalapp/Signal-Desktop/issues/2610, https://github.com/signalapp/Signal-Desktop/issues/2600
* AUR package of Skype using patchelf to link to glibc 2.27: https://aur.archlinux.org/cgit/aur.git/commit/?h=skypeforlinux-preview-bin&id=e3fa08c20b44

**Comment by lucasvinhas** [comment]
I'm with the same problem

**Comment by d0sto** [comment]
I'm also facing the same problem

**Comment by CrossR** [comment]
I've tagged this as an "electron-core" issue, since that seems to be the case? Or at least its a problem for electron, not necessarily that electron is the one at fault here.

The upstream issue seems to be : https://github.com/electron/electron/issues/13972

**Comment by K900** [comment]
That's probably it, yeah. I can send you a fixed Electron binary if you want to test.

**Comment by nesmyslny** [comment]
For people, who use [Oni from AUR](https://aur.archlinux.org/packages/oni/).

I followed the example of the [Skype AUR package](https://aur.archlinux.org/cgit/aur.git/commit/?h=skypeforlinux-preview-bin&id=e3fa08c20b44) and used patchelf to make Oni use a local copy of glibc 2.27.

Seems to work, but I cannot guarantee, that everything works. Please use it with caution and at your own risk.

Here's the hack:

```
mkdir /opt/oni/glibc
cd /opt/oni/glibc
curl -O https://archive.archlinux.org/packages/g/glibc/glibc-2.27-3-x86_64.pkg.tar.xz
tar xJf glibc-2.27-3-x86_64.pkg.tar.xz
patchelf --set-interpreter "/opt/oni/glibc/usr/lib/ld-linux-x86-64.so.2" ../oni
patchelf --set-rpath "/opt/oni:/opt/oni/glibc/usr/lib" ../oni
```

**Comment by NickGeek** [comment]
I modified the AUR package for my electron app to simply use the community electron instead of bundling it: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=micropad

**Comment by badosu** [comment]
@nesmyslny @NickGeek Thanks for reporting.

I'll update the AUR package to not use glibc 2.28 until this is fixed.

**Comment by lucasvinhas** [comment]
I think the problem is fixed. i've  upgraded glibs to glibs2.28-4 and oni is launching without any problem

**Comment by K900** [comment]
It's not fixed correctly yet - Electron 2.0.8 should contain a proper fix. Once that's out, Oni will need to update to that.

**Comment by multikatt** [comment]
Electron 2.0.8 has now been released!

**Comment by aiya000** [comment]
I still have the problem (maybe, this is fixed over the time),
but I could use a workaround on my CLI `$ electron /opt/oni/resources/app` :D

onivim is great!! thanks :D

**Comment by CrossR** [comment]
If you are on `0.3.6` @aiya000 then it hasn't got the fix in yet, which would explain this.

Though maybe now this is sorted, we should look at getting a release out sooner rather than later.

**Comment by aiya000** [comment]
@CrossR  I installed `0.3.6-1` on my arch-linux :dog2: 

```
$ aurma -Ss oni
aur/oni 0.3.6-1 (23, 2.33625) [installed]
    An IDE built around Neovim
```

Is this older?

**Comment by badosu** [comment]
Yes, this is not master.

We need `oni-git` for an installation using code from `master`.

**Comment by aiya000** [comment]
I misunderstood :joy:

I'll try to build my own.

Thank you so much!
